### ISSUE TITLE
is not possible to redirect the project?

### ISSUE THREAD

**Issue by aztrock** [niwinz/django-sse#21]
no possibility of directing the project to asyncio? or asyncio-sse?

can use realtime with django in great measure, and using async uwsgi or gunicorn workers.

**Comment by niwinz** [comment]
Yes, it is possible. But running it in async environment does not make django automatically async. Every api on django is strictly sync and it is very inneficient for async purposes. For it, i have abandoned this package, because making async apps with django on core it not make sense.

In any case, if you want continue the devolpment and try make it run under asyncio, I can transfer the repo to you  without any problem. I do not have plans to continue development of this package.
